import tailwindClasses from "./generated/classes";

describe("tailwindClassesRegex", () => {
  test.each(tailwindClasses)("the regex matches %s", (className) => {
    const startColon = "(focus|hover|lg|md|sm|xl):";

    const dashStart = "-(m[blrtxy]?|rotate|skew|space|translate)";

    const startDash = [
      "align",
      "bg",
      "border",
      "bottom",
      "box",
      "break",
      "clear",
      "col",
      "content",
      "cursor",
      "delay",
      "divide",
      "duration",
      "ease",
      "flex",
      "float",
      "flow",
      "font",
      "gap",
      "grid",
      "h",
      "inline",
      "inset",
      "items",
      "justify",
      "leading",
      "left",
      "list",
      "m[blrtxy]?",
      "max",
      "min",
      "not",
      "object",
      "opacity",
      "order",
      "origin",
      "outline",
      "overflow",
      "p[blrtxy]?",
      "placeholder",
      "resize",
      "right",
      "rotate",
      "rounded",
      "row",
      "scale",
      "scrolling",
      "select",
      "self",
      "shadow",
      "skew",
      "space",
      "sr",
      "stroke",
      "table",
      "text",
      "top",
      "tracking",
      "transform",
      "transition",
      "translate",
      "w",
      "whitespace",
      "z",
      "pointer-events",
    ];

    const equals = [
      "absolute",
      "antialiased",
      "appearance-none",
      "block",
      "border",
      "capitalize",
      "clearfix",
      "container",
      "fill-current",
      "fixed",
      "flex",
      "grid",
      "hidden",
      "inline",
      "invisible",
      "italic",
      "line-through",
      "lowercase",
      "no-underline",
      "normal-case",
      "relative",
      "resize",
      "rounded",
      "shadow",
      "static",
      "sticky",
      "subpixel-antialiased",
      "table",
      "transform",
      "transition",
      "truncate",
      "underline",
      "uppercase",
      "visible",
    ];

    const regexString = `(^(${equals.join(
      "|"
    )}$)|^(${startColon}|${dashStart}|(${startDash.join("|")})-))`;

    const regex = new RegExp(regexString);
    expect(className).toMatch(regex);
  });
});
